# Site settings
name: 程橙有个小橙子
email: m18419067500@163.com
author: CLR
url: http://IAmChengZi.github.io
resume_site: http://www.hifreud.com/Resume.io/
github: https://github.com/iamchengzi/
baseurl: ""
description: Actually, less is more!
meta_description: 程蕾蓉;个人博客;热爱生命;用心生活;努力向上;顺其自然
motto: Life sucks,but you are gonna like it.
banner: 梦想很容易丢，所以要快点抓住。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: iamchengzi
# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9


theme: jekyll-theme-cayman
